stages:
  prepare:
    cmd: python data_prep.py
    deps:
      - data_prep.py
    outs:
      - outs/prepared_df.csv

  process:
    cmd: python data_process.py
    deps:
      - data_process.py
      - outs/prepared_df.csv
    outs:
      - outs/processed_test_X.csv
      - outs/processed_test_y.csv
      - outs/processed_train_X.csv
      - outs/processed_train_y.csv

  train:
    cmd: python data_train.py
    deps:
      - data_train.py
      - outs/processed_test_X.csv
      - outs/processed_test_y.csv
      - outs/processed_train_X.csv
      - outs/processed_train_y.csv

    outs:
      - conf_matrix.png
      
    metrics:
      - metrics.json:
          cache: false 
