name: dvc-pipe
on: [push]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: iterative/setup-dvc@v1
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Env
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Post reports as comments in GitHub PRs
          dvc repro
          git fetch --prune

          echo "## Metrics" >> report.md
          dvc metrics diff --md main >> report.md

          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          
          cml comment create report.md
