name: churn-project-env
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip<=23.3.1
  - pip:
    - mlflow==2.11.3
    - numpy==1.26.4
    - pandas==2.2.1
    - psutil==5.9.0
    - scikit-learn==1.2.2
    - scipy==1.12.0
    - sklearn-features==0.0.2
    - imblearn
    - seaborn
    - xgboost
